
openapi: 3.0.1
info:
  title: Fujitsu API
  version: 1.0.0
  description: |
    Food delivery application API that calculates the delivery fee for couriers 
    based on regional base fees, vehicle type, and weather conditions.
servers:
  - url: http://localhost:8080/
    description: Local development server

externalDocs:
  url: https://swagger.io/specification/
  description: Find more information about OAS3.0 standard.


tags:
  - name: Application
    description: API for delivery fee calculation.
  - name: Delivery Fee

paths:
  /api/delivery-fee:
    get:
      operationId: getDeliveryFee
      tags:
        - Delivery Fee
      summary: Calculates delivery fee
      description: |
        Calculates the delivery fee based on the provided city, vehicle type, and optionally a timestamp.
      parameters:
        - $ref: '#/components/parameters/City'
        - $ref: '#/components/parameters/VehicleType'
        - $ref: '#/components/parameters/Timestamp'
      responses:
        '200':
          description: Successful response with calculated delivery fee.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fee'
        '403':
          description: Weather data not available for chosen region.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    City:
      name: city
      in: query
      description: Name of the city for delivery.
      required: true
      schema:
        type: string

    VehicleType:
      name: vehicleType
      in: query
      description: Type of vehicle used for delivery.
      required: true
      schema:
        type: string
        enum: [ "bike", "car", "scooter" ]

    Timestamp:
      name: timestamp
      in: query
      description: Optional timestamp to base fee calculation on weather at that time.
      required: false
      schema:
        type: integer
        format: int64

  schemas:
    Fee:
      type: object
      properties:
        amount:
          type: number
          format: float
          example: 4.50
        currency:
          type: string
          example: "EUR"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Weather data not available for chosen region."