openapi: 3.1.1
info:
  title: Fujitsu API
  version: 1.0.0
  description: |
    Food delivery application API that calculates the delivery fee for couriers 
    based on regional base fees, vehicle type, and weather conditions.

servers:
  - url: http://localhost:8080/
    description: Local development server

externalDocs:
  url: https://swagger.io/specification/
  description: Find more information about OAS3.0 standard.

tags:
  - name: Application
    description: API for delivery fee calculation.
  - name: Delivery Fee

paths:
  /fee:
    get:
      operationId: getFee
      tags:
        - Delivery Fee
      summary: Returns delivery fee
      description: |
        Calculates the delivery fee based on the provided location and delivery transport type.
      parameters:
        - $ref: '#/components/parameters/Location'
        - $ref: '#/components/parameters/DeliveryTransport'
      responses:
        '200':
          description: Successful response with calculated delivery fee.
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Fee'
        '400':
          description: Bad request (invalid parameters).
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Fee:
      type: object
      properties:
        amount:
          type: number
          format: float
        currency:
          type: string
          example: "EUR"

    WeatherCondition:
      type: object
      properties:
        id:
          type: integer
          description: Id of the WeatherCondition
          example: 1
        stationName:
          type: string
          description: Name of the station, from where weather condition info comes
          example: Tallinn-Harku
        wmoStationCode:
          type: integer
          description: WMO code of the station
          example: 26038
        airTemperature:
          type: float
          description: Air temperature
          example: 4.7
        windSpeed:
          type: float
          description: Wind speed
          example: 7.8
        weatherPhenomenon:
          type: string
          description: Observed weather phenomenon
          example: CLEAR
          enum:
            - CLEAR
            - FEW_CLOUDS
            - VARIABLE_CLOUDS
            - CLOUDY_WITH_CLEAR_SPELLS
            - OVERCAST
            - LIGHT_SNOW_SHOWER
            - MODERATE_SNOW_SHOWER
            - HEAVY_SNOW_SHOWER
            - LIGHT_RAIN
            - MODERATE_RAIN
            - HEAVY_RAIN
            - GLAZE
            - LIGHT_SLEET
            - MODERATE_SLEET
            - LIGHT_SNOWFALL
            - MODERATE_SNOWFALL
            - HEAVY_SNOWFALL
            - HAIL
            - MIST
            - FOG
        timestamp:
          type: integer
          format: int64
          description: Integer64 timestamp in seconds since epoch. Represents timestamp
                       when the measurement was taken
          example: 1742045290



    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid location provided."

  parameters:
    Location:
      name: location
      in: query
      description: Delivery location
      required: true
      schema:
        type: string

    DeliveryTransport:
      name: deliveryTransport
      in: query
      description: Delivery transport type
      required: true
      schema:
        type: string
        enum: [ "bike", "car", "scooter" ]
