package com.fujitsu.trialtask.enums;

public enum WeatherPhenomenon {
    CLEAR,
    FEW_CLOUDS,
    VARIABLE_CLOUDS,
    CLOUDY_WITH_CLEAR_SPELLS,
    OVERCAST,
    LIGHT_SNOW_SHOWER,
    MODERATE_SNOW_SHOWER,
    HEAVY_SNOW_SHOWER,
    LIGHT_RAIN,
    MODERATE_RAIN,
    HEAVY_RAIN,
    GLAZE,
    LIGHT_SLEET,
    MODERATE_SLEET,
    LIGHT_SNOWFALL,
    MODERATE_SNOWFALL,
    HEAVY_SNOWFALL,
    HAIL,
    MIST,
    FOG;
}
